--alter table prep.location rename last_updated to last_modified;

--DROP SEQUENCE stage.currently_id_seq cascade;

--CREATE SEQUENCE stage.currently_id_seq
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 2147483647
--	START 1
--	CACHE 1
--	NO CYCLE;
--
--truncate stage.currently;

drop table if exists stage.location cascade;
CREATE TABLE if not exists stage.location (
    --id serial PRIMARY KEY,
    city_name VARCHAR(100),
    region VARCHAR (50),
    country VARCHAR(50),
    latitude DECIMAL(8,6),
    longitude DECIMAL(9,6),
    timezone_id VARCHAR(50),
    local_time_epoch BIGINT,
    local_time VARCHAR(30),
	process_uuid text,
	zipcode varchar (30)
);

drop table if exists prep.location cascade;
CREATE TABLE if not exists prep.location (
    --id serial PRIMARY KEY,
    city_name VARCHAR(100),
    region VARCHAR (50),
    country VARCHAR(50),
    latitude DECIMAL(8,6),
    longitude DECIMAL(9,6),
    timezone_id VARCHAR(50),
    local_time_epoch BIGINT,
    local_time VARCHAR(30),
	process_uuid text,    
	zipcode varchar (30),
    sys_rec_hash text,
    sys_cdc_flag text
);

drop table if exists target.location cascade;
CREATE TABLE if not exists target.location (
    --id serial PRIMARY KEY,
    city_name VARCHAR(100),
    region VARCHAR (50),
    country VARCHAR(50),
    latitude DECIMAL(8,6),
    longitude DECIMAL(9,6),
    timezone_id VARCHAR(50),
    local_time_epoch BIGINT,
    local_time VARCHAR(30),
	process_uuid text,
	zipcode varchar (30),
	sys_rec_hash text,
    sys_start_date date,
    sys_end_date date,
    sys_is_active BOOL
    
);

drop table if exists stage.currently cascade;
create table if not exists stage.currently (
	--id serial primary key,
	last_updated_epoch bigint,
	last_updated timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	vis_km float,
	vis_miles float,
	uv float,
	gust_mph float,
	gust_kph float,
	process_uuid text,
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text
);

drop table if exists prep.currently cascade;
create table if not exists prep.currently (
	--id serial primary key,
	last_updated_epoch bigint,
	last_updated timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	vis_km float,
	vis_miles float,
	uv float,
	gust_mph float,
	gust_kph float,
	process_uuid text,	
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text,
	sys_rec_hash text,
	sys_cdc_flag text
--    sys_last_modified TIMESTAMP,
--    sys_is_active BOOL
);

drop table if exists target.currently cascade;
create table if not exists target.currently (
	--id serial primary key,
	last_updated_epoch bigint,
	last_updated timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	vis_km float,
	vis_miles float,
	uv float,
	gust_mph float,
	gust_kph float,
	process_uuid text,
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text,
	sys_rec_hash text,
    sys_start_date date,
    sys_end_date date,
    sys_is_active Bool
);


drop table if exists stage.daily cascade;
create table if not exists stage.daily (
	--id serial primary key,
--	date date,
--	date_epoch bigint,
	maxtemp_c float,
	maxtemp_f float,
	mintemp_c float,
	mintemp_f float,
	avgtemp_c float,
	avgtemp_f float,
	maxwind_mph float,
	maxwind_kph float,
	totalprecip_mm float,
	totalprecip_in float,
	totalsnow_cm float,
	avgvis_km float,
	avgvis_miles float,
	avghumidity float,
	daily_will_it_rain float,
	daily_chance_of_rain float,
	daily_will_it_snow float,
	daily_chance_of_snow float,
	uv float,
	process_uuid text,
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text
);

drop table if exists prep.daily cascade;
create table if not exists prep.daily (
	--id serial primary key,
--	date date,
--	date_epoch bigint,
	maxtemp_c float,
	maxtemp_f float,
	mintemp_c float,
	mintemp_f float,
	avgtemp_c float,
	avgtemp_f float,
	maxwind_mph float,
	maxwind_kph float,
	totalprecip_mm float,
	totalprecip_in float,
	totalsnow_cm float,
	avgvis_km float,
	avgvis_miles float,
	avghumidity float,
	daily_will_it_rain float,
	daily_chance_of_rain float,
	daily_will_it_snow float,
	daily_chance_of_snow float,
	uv float,
	process_uuid text,
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text,
	sys_rec_hash text,
	sys_cdc_flag text
--	sys_last_modified TIMESTAMP,
--	sys_is_active BOOL
);

drop table if exists target.daily cascade;
create table if not exists target.daily (
	--id serial primary key,
--	date date,
--	date_epoch bigint,
	maxtemp_c float,
	maxtemp_f float,
	mintemp_c float,
	mintemp_f float,
	avgtemp_c float,
	avgtemp_f float,
	maxwind_mph float,
	maxwind_kph float,
	totalprecip_mm float,
	totalprecip_in float,
	totalsnow_cm float,
	avgvis_km float,
	avgvis_miles float,
	avghumidity float,
	daily_will_it_rain float,
	daily_chance_of_rain float,
	daily_will_it_snow float,
	daily_chance_of_snow float,
	uv float,
	process_uuid text,
	zipcode varchar (30),
	condition_text text,
	condition_icon text,
	condition_code text,
	sys_rec_hash text,
	sys_start_date date,
	sys_end_date date,
	sys_is_active Bool
);

drop table if exists stage.hourly cascade;
create table if not exists stage.hourly (
	--id serial primary key,
	time_epoch bigint,
	time timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	snow_cm float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	will_it_rain float,
	chance_of_rain float,
	will_it_snow float,
	chance_of_snow float,
	vis_km float,
	vis_miles float,
	gust_mph float,
	gust_kph float,
	uv float,
	condition_text text,
	condition_icon text,
	condition_code text,
	date date,
	date_epoch bigint,
	process_uuid text,
	zipcode varchar (30)
	
);

drop table if exists prep.hourly cascade;
create table if not exists prep.hourly (
	--id serial primary key,
	time_epoch bigint,
	time timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	snow_cm float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	will_it_rain float,
	chance_of_rain float,
	will_it_snow float,
	chance_of_snow float,
	vis_km float,
	vis_miles float,
	gust_mph float,
	gust_kph float,
	uv float,
	condition_text text,
	condition_icon text,
	condition_code text,
	date date,
	date_epoch bigint,
	process_uuid text,
	zipcode varchar (30),
	sys_rec_hash text,
	sys_cdc_flag text
--	sys_last_modified TIMESTAMP,
--	sys_is_active BOOL
);

drop table if exists target.hourly  cascade;
create table if not exists target.hourly (
	--id serial primary key,
	time_epoch bigint,
	time timestamp,
	temp_c float,
	temp_f float,
	is_day float,
	wind_mph float,
	wind_kph float,
	wind_degree float,
	wind_dir text,
	pressure_mb float,
	pressure_in float,
	precip_mm float,
	precip_in float,
	snow_cm float,
	humidity float,
	cloud float,
	feelslike_c float,
	feelslike_f float,
	windchill_c float,
	windchill_f float,
	heatindex_c float,
	heatindex_f float,
	dewpoint_c float,
	dewpoint_f float,
	will_it_rain float,
	chance_of_rain float,
	will_it_snow float,
	chance_of_snow float,
	vis_km float,
	vis_miles float,
	gust_mph float,
	gust_kph float,
	uv float,
	condition_text text,
	condition_icon text,
	condition_code text,
	date date,
	date_epoch bigint,
	process_uuid text,
	zipcode varchar (30),
	sys_rec_hash text,
	sys_start_date date,
	sys_end_date date,
	sys_is_active Bool
);